Repository sassoftware/viya4-deployment, pull requests merged in 2021-11, with the labels that each got.

#160 add cluster-api label support
  roles/vdm/tasks/deploy.yaml
Labels: enhancement

#161 Update kubeconfig filepath in DockerUsage.md
  docs/user/DockerUsage.md
Labels: documentation

#164 Adding in check or rc on error condition
  roles/vdm/tasks/deploy.yaml
Labels: bug

#167 Adjusting failure check for deploy_logging_open.sh script
  roles/monitoring/tasks/cluster-logging.yaml
Labels: enhancement

#148 add INGRESS_MODE suppport
  README.md
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/common/tasks/main.yaml
Labels: documentation, enhancement
