Repository sassoftware/viya4-deployment, pull requests merged in 2021-06, with the labels that each got.

#104 Ingress class
  roles/vdm/tasks/ingress.yaml
  roles/vdm/templates/transformers/nginx-ingressclass.yaml
Labels: enhancement

#105 Basic contour install
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cert-manager.yaml
  roles/baseline/tasks/contour.yaml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/baseline/tasks/main.yaml
  roles/baseline/tasks/nfs-subdir-external-provisioner.yaml
Labels: enhancement

#106 bump viya4-orders-cli version
  roles/vdm/defaults/main.yaml
Labels: dependencies

#107 add elastic folder check
  roles/vdm/tasks/elasticsearch.yaml
  roles/vdm/tasks/main.yaml
Labels: bug, enhancement

#111 enable overlays for minimal sizing
  README.md
  docs/CONFIG-VARS.md
  roles/common/tasks/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/sizing.yaml
Labels: enhancement

#112 Enable cluster-autoscaler on AWS
  README.md
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cluster-autoscaler.yaml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
Labels: documentation, enhancement
