Repository sassoftware/viya4-deployment, pull requests merged in 2022-06, with the labels that each got.

#233 (IAC-562) Update Kustomize Doc
  README.md
Labels: documentation

#236 (IAC-553) move to kubectl 1.22.10 to support k8s 1.23
  Dockerfile
  docs/user/Dependencies.md
Labels: documentation, enhancement

#240 fix: (IAC-508) Update release reference in troubleshooting doc
  docs/Troubleshooting.md
Labels: documentation

#246 (IAC-593) Updates to handle OpenSSL Support for Viya 4 Monitoring
  roles/monitoring/vars/main.yaml
Labels: enhancement
