Repository sassoftware/viya4-deployment, pull requests merged in 2022-10, with the labels that each got.

#306 5.5.0 - October 3, 2022
  docs/CONFIG-VARS.md
  examples/ansible-vars-iac.yaml
  examples/ansible-vars.yaml
  playbooks/playbook.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cert-manager.yaml
  roles/baseline/tasks/ebs-csi-driver.yaml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
  roles/monitoring/defaults/main.yaml
  roles/monitoring/vars/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/start_stop.yaml
  roles/vdm/templates/transformers/schedule-start-stop.yaml
Labels: bug, enhancement

#303 feat: (IAC-644) Add DaC support for crunchy v5
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/postgres/gcp-cloud-sql-proxy.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
  roles/vdm/tasks/postgres/postgres.yaml
  roles/vdm/templates/generators/mirror.v2.yaml
  roles/vdm/templates/generators/postgres-secrets.yaml
  roles/vdm/templates/generators/sql-proxy-serviceaccountkey.yaml
  roles/vdm/templates/postgres-user.env
  roles/vdm/templates/transformers/dataserver-transformer.yaml
Labels: enhancement

#289 (IAC-725) docs: Update SingleStore.md
  docs/user/SingleStore.md
Labels: documentation

#311 feat: (IAC-754) Allow for extra external DBs & Configurable External DB SSL
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/templates/resources/platform-postgres-dataserver.yaml
  roles/vdm/templates/transformers/dataserver-transformer.yaml
Labels: enhancement

#307 feat: (IAC-739) Support a CDSPostgreSQL instance for Crunchy v5
  docs/CONFIG-VARS.md
  roles/vdm/tasks/cds.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres.yaml
Labels: documentation, enhancement

#312 feat: (IAC-756): Update crunchy v5 tuning transformer
  docs/user/Multi-Tenancy.md
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
Labels: documentation, enhancement

#315 5.6.0 - October 20, 2022
  docs/CONFIG-VARS.md
  docs/user/Multi-Tenancy.md
  roles/vdm/tasks/cds.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/postgres/gcp-cloud-sql-proxy.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
  roles/vdm/tasks/postgres/postgres.yaml
  roles/vdm/templates/generators/mirror.v2.yaml
  roles/vdm/templates/generators/postgres-secrets.yaml
  roles/vdm/templates/generators/sql-proxy-serviceaccountkey.yaml
  roles/vdm/templates/postgres-user.env
  roles/vdm/templates/resources/platform-postgres-dataserver.yaml
  roles/vdm/templates/transformers/dataserver-transformer.yaml
Labels: bug, documentation, enhancement

#318 feat: (IAC-739) Remove automatic kustomization.yaml content for sas-planning overlays
  roles/vdm/tasks/cds.yaml
  roles/vdm/tasks/main.yaml
Labels: enhancement

#323 5.6.0 - October 20, 2022 -new PR
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/cds.yaml
  roles/vdm/tasks/main.yaml
Labels: documentation, enhancement

#309 feat: (IAC-557) Add GKE pod subnet cidr to LOADBALANCER_SOURCE_RANGES
  roles/common/tasks/main.yaml
Labels: enhancement

#314 fix: (IAC-524): Modify sitedefault.yml file to include required missing ldap.connection.url property
  examples/sitedefault.yaml
  roles/vdm/files/sitedefault.yaml
Labels: bug

#276 feat: (IAC-552) (IAC-664) Integrate with the Deployment Operator and Orchestration tooling for SAS Viya deployments
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/AnsibleUsage.md
  docs/user/Dependencies.md
  docs/user/DockerUsage.md
  playbooks/playbook.yaml
  requirements.txt
  requirements.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/task-validations.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/kustomize.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/sizing.yaml
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/deployment_operator_kustomization.yaml
Labels: documentation, enhancement

#310 fix: (IAC-742) Lookup cluster K8S version information from within DAC
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
Labels: bug
