Repository sassoftware/viya4-deployment, pull requests merged in 2022-12, with the labels that each got.

#345 feat: (IAC-664) Update Docker Run Calls and Create License Folder
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/templates/generators/sas-license.yaml
Labels: enhancement

#350 fix: (IAC-664) Move License Folder & Update Docker Run Call
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/templates/generators/sas-license.yaml
Labels: bug

#351 feat: (IAC-770) use k8s.core.k8s_info module not kubectl to avoid ansible error output
  roles/vdm/tasks/postgres/pg_config.yaml
Labels: enhancement

#353 feat: (IAC-486) Update default cadence version value
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
Labels: enhancement

#355 docs: (IAC-809) Deployment Operator Documentation Updates
  docs/CONFIG-VARS.md
Labels: documentation

#356 docs: (IAC-560): Added clarification on the users added to the embedded OpenLDAP
  README.md
Labels: documentation

#359 docs: (IAC-809) Deployment Operator Documentation Updates
  docs/CONFIG-VARS.md
Labels: documentation

#360 docs: (IAC-743): Add update information in README.md
  README.md
Labels: documentation

#361 5.7.0 - December 19, 2022
  Dockerfile
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/AnsibleUsage.md
  docs/user/Dependencies.md
  docs/user/DockerUsage.md
  examples/sitedefault.yaml
  playbooks/playbook.yaml
  requirements.txt
  requirements.yaml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/task-validations.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/files/sitedefault.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/kustomize.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
  roles/vdm/tasks/sizing.yaml
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/deployment_operator_kustomization.yaml
  roles/vdm/templates/generators/sas-license.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
  roles/vdm/templates/transformers/postgres-storage-transformer.v3.yaml
  roles/vdm/vars/main.yaml
Labels: bug, documentation, enhancement
