Repository sassoftware/viya4-deployment, pull requests merged in 2022-09, with the labels that each got.

#291 docs: (IAC-692) Multi-tenancy README updates from Pub
  docs/CONFIG-VARS.md
  docs/user/Multi-Tenancy.md
  examples/multi-tenancy/openldap/openldap-modify-mt-users-groups.yaml
Labels: documentation

#293 feat: (IAC-582) Support configuring schedule-start-stop.yaml
  docs/CONFIG-VARS.md
  examples/ansible-vars-iac.yaml
  examples/ansible-vars.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/start_stop.yaml
  roles/vdm/templates/transformers/schedule-start-stop.yaml
Labels: documentation, enhancement

#294 feat: (IAC-582) Allow user to specify either V4_CFG_VIYA_START_SCHEDULE or V4_CFG_VIYA_STOP_SCHEDULE
  docs/CONFIG-VARS.md
  roles/vdm/tasks/start_stop.yaml
  roles/vdm/templates/transformers/schedule-start-stop.yaml
Labels: documentation, enhancement

#299 feat: (IAC-707) Remove CERT_MANAGER_ENABLED and use V4_CFG_TLS_GENERATOR
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cert-manager.yaml
Labels: documentation, enhancement

#298 feat: (IAC-667) add the ability to install the aws ebs csi driver in DAC
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
Labels: enhancement

#300 fix: (IAC-640) Remove V4M_OSD_NODEPORT_ENABLE configuration variable usage from DAC
  docs/CONFIG-VARS.md
  roles/monitoring/defaults/main.yaml
  roles/monitoring/vars/main.yaml
Labels: bug, documentation

#305 feat: (IAC-723) Uninstall baseline components last during uninstall phase
  playbooks/playbook.yaml
Labels: enhancement
