Repository sassoftware/viya4-deployment, pull requests merged in 2022-04, with the labels that each got.

#202 (IAC-483) Conditionally Patch ingress-nginx Config
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: enhancement

#205 Monthly Release - 4.10.0
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: documentation, enhancement

#208 (IAC-509) Update default metrics-server helm chart version
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#209 Monthly Release - 4.11.0
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#211 (IAC-525) Update to handle new SAS_CERTIFICATE_GENERATOR default.
  roles/vdm/templates/generators/customer-provided-merge-sas-certframe-configmap.yaml
Labels: enhancement

#213 (IAC-525) update ansible task for certificate configuration
  roles/vdm/tasks/tls.yaml
Labels: enhancement

#214 Monthly Release - 4.12.0
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/generators/customer-provided-merge-sas-certframe-configmap.yaml
Labels: enhancement

#215 (IAC-528) added git share directive for viya4-deployment
  Dockerfile
Labels: bug

#216 (IAC-528) Added git share
  Dockerfile
Labels: bug

#217 4.12.1 - April 28, 2022
  Dockerfile
Labels: bug
