Repository sassoftware/viya4-deployment, pull requests merged in 2022-05, with the labels that each got.

#204 (IAC-333) Adding in hsts-max-age for security compliance.
  roles/baseline/defaults/main.yml
Labels: bug

#222 (IAC-540) support for openssl certificate generator with openssl-generated ingress certificates
  docs/CONFIG-VARS.md
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/resources/openssl-generated-ingress-certificate.yaml
Labels: documentation, enhancement

#201 (IAC-376) Use Private Jump IP if Public not Present in tfstate
  roles/common/tasks/main.yaml
Labels: enhancement

#218 (IAC-518) Update Default CERT_MANAGER_CHART_VERSION to 1.7.2
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement
