Repository sassoftware/viya4-deployment, pull requests merged in 2022-11, with the labels that each got.

#327 fix: (IAC-742) Lookup cluster K8S version information from within DAC
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
Labels: bug

#329 feat: (IAC-701) Add support for crunchy-storage-transformer and configuration vars, update postgres-storage-transfomer
  docs/CONFIG-VARS.md
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
  roles/vdm/templates/transformers/postgres-storage-transformer.v3.yaml
  roles/vdm/vars/main.yaml
Labels: bug, enhancement

#332 (iac-701) Use 'sas' as default storage class name for postgres and pgbackrest PVCs
  docs/CONFIG-VARS.md
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
Labels: enhancement

#334 fix: (iac-788) align V4_CFG_MANAGE_STORAGE default with docs
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
Labels: documentation

#328 feat: (IAC-552) (IAC-664) Integrate with the Deployment Operator and Orchestration tooling for SAS Viya deployments
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/AnsibleUsage.md
  docs/user/Dependencies.md
  docs/user/DockerUsage.md
  playbooks/playbook.yaml
  requirements.txt
  requirements.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/task-validations.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/kustomize.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/sizing.yaml
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/deployment_operator_kustomization.yaml
Labels: documentation, enhancement

#343 docs: (IAC-664): Update troubleshoot guide for DO
  docs/Troubleshooting.md
Labels: documentation

#342 docs: (IAC-552): Update Dependencies.md for min Docker Version
  docs/user/Dependencies.md
Labels: documentation
