Repository sassoftware/viya4-deployment, pull requests merged in 2022-08, with the labels that each got.

#267 doc: (IAC-441) Updated the CAS resources and Postgres sections
  docs/user/Multi-Tenancy.md
Labels: documentation

#251 (IAC-581) V4_CFG_TLS_TRUSTED_CA_CERTS is required for TLS enabled Viya on AWS clusters
  docs/CONFIG-VARS.md
  docs/user/TrustedCACerts.md
Labels: documentation

#271 fix: (IAC-645) Updated CAS transformer templates for CAS workers and backup
  roles/vdm/templates/transformers/cas-manage-backup.yaml
  roles/vdm/templates/transformers/cas-manage-workers.yaml
Labels: bug

#224 (IAC-552) Integrate with SAS Viya Orchestration tooling for SAS Viya install and uninstall
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  requirements.txt
  requirements.yaml
  roles/common/tasks/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/kustomize.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/mirror.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/sizing.yaml
  roles/vdm/tasks/tls.yaml
Labels: documentation, enhancement

#281 (IAC-658): fix: Updating default value for V4MT_TENANT_CAS_CUSTOMIZATION
  roles/multi-tenancy/defaults/main.yml
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
Labels: bug

#277 feat: (IAC-629) Support SingleStore (DAC)
  README.md
  docs/user/SingleStore.md
  roles/vdm/library/siteconfig_info.py
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/kustomization.yaml
Labels: documentation, enhancement

#272 feat: (IAC-564) SAS Viya Startup Sequencer - Add entry in kustomization.yaml
  roles/vdm/tasks/main.yaml
Labels: enhancement

#282 feat: (IAC-564): Reverted the changes for sequencer
  roles/vdm/tasks/main.yaml
Labels: enhancement

#283 5.3.0 - August 18, 2022
  README.md
  docs/user/SingleStore.md
  roles/vdm/library/siteconfig_info.py
  roles/vdm/tasks/tls.yaml
  roles/vdm/templates/kustomization.yaml
Labels: enhancement

#286 feat: (IAC-673): DAC - support K8s 1.24 deployment
  Dockerfile
  docs/user/Dependencies.md
Labels: enhancement

#287 fix: (IAC-689) add new exclusion for storageclass patch transformer
  roles/vdm/templates/transformers/sas-storageclass.yaml
Labels: bug

#288 feat: (IAC-687) Upgrade Ingress-nginx to v1.3.0 to support K8s 1.24
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#290 feat: (IAC-636) Update cert-manager version 1.9.1
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#285 fix: (IAC-670) Correct case typo for alertmanagerSpec
  roles/monitoring/templates/user-values-prom-operator.yaml
Labels: bug
