Repository sassoftware/viya4-deployment, pull requests merged in 2022-07, with the labels that each got.

#245 feat: (IAC-480) Change default certificate generator to openssl
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/vdm/defaults/main.yaml
Labels: documentation, enhancement

#255 fix: (IAC-586) Correct the ingress-nginx annotations
  roles/baseline/defaults/main.yml
Labels: bug

#254 (IAC-617) Wrong variable is being defaulted to /export
  roles/baseline/defaults/main.yml
Labels: bug

#256 feat: (IAC-620) Update deploy command to use CRD server-side apply
  roles/vdm/tasks/deploy.yaml
Labels: enhancement

#258 fix: (IAC-480) Add Default TLS Generator Variable for Monitoring
  roles/monitoring/vars/main.yaml
Labels: bug

#259 fix: (IAC-630) Fix the V4_CFG_CADENCE_NAME conditionals in the TLS Task
  roles/vdm/tasks/tls.yaml
Labels: bug

#261 fix: (IAC-630) Fix the V4_CFG_CADENCE_NAME conditionals in the Postgres Task
  roles/vdm/tasks/postgres/postgres.yaml
Labels: bug

#262 5.1.0 - July 21, 2022
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/monitoring/vars/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/postgres/postgres.yaml
  roles/vdm/tasks/tls.yaml
Labels: bug, documentation, enhancement

#263 feat: (IAC-397) Add password setting support for kibana new user logadm
  docs/CONFIG-VARS.md
  roles/monitoring/defaults/main.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/vars/main.yaml
Labels: enhancement

#264 feat: (IAC-568) remove kibanaserver, logcollector and metricgetter id/passwords from "cluster-logging - output credentials" task
  roles/monitoring/tasks/cluster-logging.yaml
Labels: enhancement

#265 fix: (IAC-556) Incorrect tls.key in alertmanager-ingress-tls-secret
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/vdm/tasks/deploy.yaml
Labels: bug
