Repository sassoftware/viya4-deployment, pull requests merged in 2023-08, with the labels that each got.

#466 feat: (IAC-1107) Update Google Cloud CLI to 440.0.0
  Dockerfile
  docs/user/Dependencies.md
Labels: documentation, enhancement

#461 fix: (IAC-1004) Remove sas-connect-customer-provided-ingress-certificate-tls-certframe-transformer.yaml
  roles/vdm/tasks/connect.yaml
  roles/vdm/templates/transformers/sas-connect-customer-provided-ingress-certificate-tls-certframe-transformer.yaml
Labels: bug

#473 feat: (IAC-1047) Update to newer release for cluster-autoscaler in EKS
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#472 feat: (IAC-1044) update ingress-nginx default to v1.8.1
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#474 docs: (IAC-1109) Add EBS CSI Driver section to ToC in CONFIG-VARS.md
  docs/CONFIG-VARS.md
Labels: documentation

#480 feat: (IAC-1003) Update deprecated provisioner in V4M Azure storageclass
  roles/monitoring/files/azure-storageclass.yaml
Labels: enhancement

#481 feat: (IAC-1108) Multi-tenancy process change - apply podtemplates before running onboard
  docs/user/Multi-Tenancy.md
  playbooks/playbook.yaml
  roles/multi-tenancy/defaults/main.yml
  roles/multi-tenancy/tasks/main.yaml
  roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/multi-tenancy/tasks/tenant-pod-templates.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/sasdeployment_custom_resource.yaml
Labels: documentation, enhancement

#484 feat: (IAC-1147) DAC - Support K8s 1.27 in 2023.09
  Dockerfile
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#483 feat: (IAC-1155) Add Support for Setting up SAS Workload Orchestrator
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/workload_orchestrator.yaml
Labels: documentation, enhancement
