Repository sassoftware/viya4-deployment, pull requests merged in 2023-10, with the labels that each got.

#494 feat: (IAC-1170) Update Default CERT_MANAGER_CHART_VERSION to 1.13.1
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#492 fix: (IAC-1169) deploy orchestration cmd in DAC docker container fails running DAC's kubectl binary
  roles/vdm/tasks/deploy.yaml
Labels: bug

#496 fix: (IAC-1072) Add AKS pod cidr to LOADBALANCER_SOURCE_RANGES
  roles/common/tasks/main.yaml
Labels: bug

#497 docs: (IAC-1202) Transfer Tooling viya4-deployment Supplemental Doc
  docs/Troubleshooting.md
Labels: documentation

#498 docs: (IAC-1202) PostgreSQL Transfer Tooling Supplemental Doc
  docs/Troubleshooting.md
  docs/user/PostPostgreSQLDataTransfer_Experimental.md
Labels: documentation

#499 6.13.0 - October 19, 2023
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/PostPostgreSQLDataTransfer_Experimental.md
  roles/baseline/defaults/main.yml
  roles/common/tasks/main.yaml
  roles/vdm/tasks/deploy.yaml
Labels: bug, documentation, enhancement

#500 docs: (IAC-1208) Crunchy 4 PostgreSQL Transfer Tooling Experimental Doc
  docs/user/PostPostgreSQLDataTransfer_Experimental.md
Labels: documentation

#503 docs: (IAC-1208) Additional Data Transfer Doc Changes
  docs/user/PostPostgreSQLDataTransfer_Experimental.md
  docs/user/PostgreSQL.md
Labels: documentation
