Repository sassoftware/viya4-deployment, pull requests merged in 2023-03, with the labels that each got.

#402 fix: (IAC-932) restore previous nfs-data mountPath in cas-add-nfs-mount.yaml transformer
  roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
Labels: bug

#407 fix: (IAC-953): Fixed multi-tenant onboard command failure
  roles/multi-tenancy/tasks/main.yaml
  roles/orchestration-common/tasks/orchestration_tooling.yaml
Labels: bug

#403 feat: (IAC-887): Add support for tenant pod templates
  docs/user/Multi-Tenancy.md
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/multi-tenancy/tasks/tenant-pod-templates.yaml
Labels: enhancement

#405 fix: (IAC-938) filestore directory doesn't get created w/o V4_CFG_MANAGE_STORAGE
  playbooks/playbook.yaml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
  roles/monitoring/tasks/main.yaml
Labels: bug

#415 6.3.0 - March 16, 2023
  Dockerfile
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/Dependencies.md
  docs/user/Multi-Tenancy.md
  playbooks/playbook.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cluster-autoscaler.yaml
  roles/baseline/tasks/main.yaml
  roles/common/tasks/main.yaml
  roles/monitoring/defaults/main.yaml
  roles/monitoring/tasks/main.yaml
  roles/multi-tenancy/tasks/main.yaml
  roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/multi-tenancy/tasks/tenant-pod-templates.yaml
  roles/orchestration-common/defaults/main.yaml
  roles/orchestration-common/tasks/orchestration_tooling.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
  roles/vdm/tasks/sasdeployment_custom_resource.yaml
  roles/vdm/tasks/validations.yaml
  roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
Labels: bug, enhancement

#404 feat: (IAC-920) DEPLOY Flag Should Also Control the Deployment Operator Un/Installation
  docs/CONFIG-VARS.md
  roles/vdm/tasks/deployment_operator.yaml
Labels: documentation, enhancement

#417 docs: (IAC-961) Ansible Config Documentation
  docs/user/AnsibleUsage.md
Labels: documentation

#411 docs: (IAC-954) Add aws-ebs-csi-driver entry to "Prepare Kubernetes Cluster" list in README
  README.md
Labels: documentation

#418 feat: (IAC-893) Ingress-nginx service annotation added for Azure LB probing issue
  docs/Troubleshooting.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: documentation, enhancement

#410 docs: (IAC-930) sas-data-agent-server-colocated statefulset caused "/spec/volumeClaimTemplates/0/spec/storageClassName": missing value during update
  docs/Troubleshooting.md
Labels: documentation

#386 feat: (IAC-320) Provide context based routing option for Logging and Monitoring
  docs/CONFIG-VARS.md
  roles/monitoring/defaults/main.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/monitoring/templates/host-based/user-values-opensearch.yaml
  roles/monitoring/templates/host-based/user-values-osd.yaml
  roles/monitoring/templates/host-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user-values-opensearch.yaml
  roles/monitoring/templates/path-based/user-values-osd.yaml
  roles/monitoring/templates/path-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user.env
  roles/monitoring/templates/secret.yaml
  roles/monitoring/templates/user-values-pushgateway.yaml
Labels: documentation, enhancement

#412 docs: (IAC-916) V4M monitoring and logging fails to install with open-source K8s because of the missing v4m SC
  docs/CONFIG-VARS.md
Labels: documentation

#413 docs: (IAC-958) update DAC SingleStore.md to include iac-aws and oss-k8s
  docs/user/SingleStore.md
Labels: documentation
