Repository sassoftware/viya4-deployment, pull requests merged in 2023-01, with the labels that each got.

#364 feat: (IAC-486): Updated cadence version to latest lts 2022.09
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
Labels: enhancement

#349 feat: (IAC-439): Make NLB to be default load balancer for AWS
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: enhancement

#363 feat: (IAC-862) Update default metrics server helm chart version
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#348 fix: (iac-602) sas-common-backup-data-storage-class-transformer sequence issue
  roles/vdm/tasks/storage.yaml
Labels: bug

#365 feat: (IAC-693) Update kustomization.yaml indentation
  roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
  roles/vdm/templates/kustomization.yaml
Labels: enhancement

#367 feat: (IAC-439): Revert NLB changes
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: enhancement

#371 feat: (IAC-439): Updated the default load balancer created for AWS to be NLB
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/vdm/templates/resources/consul-ui.yaml
  roles/vdm/templates/resources/sas-connect-spawner-enable-loadbalancer.yaml
  roles/vdm/templates/transformers/cas-enable-external-services.yaml
Labels: enhancement

#366 feat: (IAC-720) Update \site-config\vdm\transformers with sas-bases\examples
  roles/vdm/tasks/storage.yaml
  roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
  roles/vdm/templates/transformers/compute-server-add-nfs-mount.v2.yaml
  roles/vdm/templates/transformers/launcher-nfs-mount.yaml
Labels: enhancement

#378 feat: (IAC-816) Update DAC Folder Structure
  docs/user/DeploymentDirectoryStructure.md
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/templates/deployment-operator-clusterwide.yaml
Labels: documentation, enhancement
