Repository sassoftware/viya4-deployment, pull requests merged in 2023-02, with the labels that each got.

#338 feat: (iac-770) Create new storage class for crunchy v5 PVCs
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  requirements.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cert-manager.yaml
  roles/baseline/tasks/cluster-autoscaler.yaml
  roles/baseline/tasks/contour.yaml
  roles/baseline/tasks/ebs-csi-driver.yaml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/baseline/tasks/main.yaml
  roles/baseline/tasks/metrics-server.yaml
  roles/baseline/tasks/nfs-subdir-external-provisioner.yaml
  roles/istio/tasks/main.yml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/postgres/pg_config.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
Labels: documentation, enhancement

#384 docs: (IAC-894) Add troubleshoot documentation around docker requirements.
  docs/Troubleshooting.md
Labels: documentation

#373 docs: (IAC-837) Add clarification text for V4_CFG_MANAGE_STORAGE settings
  docs/CONFIG-VARS.md
Labels: documentation

#379 feat: (IAC-849) Updates for Kustomize 4.5.7
  Dockerfile
  docs/user/Dependencies.md
  roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/validations.yaml
Labels: documentation, enhancement

#381 feat: (IAC-829) Add CAS Auto Restart Option
  docs/CONFIG-VARS.md
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/cas.yaml
  roles/vdm/templates/transformers/cas-auto-restart.yaml
Labels: documentation, enhancement

#383 feat: (IAC-842) Add V4_CFG_CERTS and conditionally download viya4-orders-cli
  docs/CONFIG-VARS.md
  docs/user/DockerVolumeMounts.md
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/assets.yaml
Labels: documentation, enhancement

#382 feat: (IAC-878) support external cds postgres
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres.yaml
  roles/vdm/templates/transformers/dataserver-transformer.yaml
  roles/vdm/vars/main.yaml
Labels: enhancement

#389 feat: (IAC-889) Support OpenSearch and OpenSearch Dashboards 2.4.1
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/templates/user-values-elasticsearch-open.yaml
  roles/monitoring/templates/user-values-opensearch.yaml
  roles/monitoring/templates/user-values-osd.yaml
Labels: enhancement

#388 feat: (IAC-874) Update default cert-manager version to 1.11.0
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#392 fix: (IAC-909) storageClasses not created during baseline install w/out V4_CFG_MANAGE_STORAGE explicitly defined
  roles/baseline/defaults/main.yml
Labels: bug

#393 6.2.0 - February 17, 2023
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  docs/user/DeploymentDirectoryStructure.md
  docs/user/DockerVolumeMounts.md
  requirements.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cert-manager.yaml
  roles/baseline/tasks/cluster-autoscaler.yaml
  roles/baseline/tasks/contour.yaml
  roles/baseline/tasks/ebs-csi-driver.yaml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/baseline/tasks/main.yaml
  roles/baseline/tasks/metrics-server.yaml
  roles/baseline/tasks/nfs-subdir-external-provisioner.yaml
  roles/istio/tasks/main.yml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/monitoring/templates/user-values-elasticsearch-open.yaml
  roles/monitoring/templates/user-values-opensearch.yaml
  roles/monitoring/templates/user-values-osd.yaml
  roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/assets.yaml
  roles/vdm/tasks/cas.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/orchestration.yaml
  roles/vdm/tasks/postgres/pg_config.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/tasks/postgres/postgres.yaml
  roles/vdm/tasks/storage.yaml
  roles/vdm/tasks/validations.yaml
  roles/vdm/templates/deployment-operator-clusterwide.yaml
  roles/vdm/templates/resources/consul-ui.yaml
  roles/vdm/templates/resources/sas-connect-spawner-enable-loadbalancer.yaml
  roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
  roles/vdm/templates/transformers/cas-auto-restart.yaml
  roles/vdm/templates/transformers/cas-enable-external-services.yaml
  roles/vdm/templates/transformers/compute-server-add-nfs-mount.v2.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
  roles/vdm/templates/transformers/dataserver-transformer.yaml
  roles/vdm/templates/transformers/launcher-nfs-mount.yaml
  roles/vdm/vars/main.yaml
Labels: bug, documentation, enhancement

#396 feat: (IAC-912): Postgres tuning transformer changes for 2023.03 cadence
  roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
Labels: enhancement

#395 feat: (IAC-911) Utilize kustomize from within the sas-orchestration image for all tasks
  Dockerfile
  docs/user/Dependencies.md
  roles/multi-tenancy/tasks/main.yaml
  roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
  roles/orchestration-common/defaults/main.yaml
  roles/orchestration-common/tasks/orchestration_tooling.yaml
  roles/vdm/tasks/deployment_operator.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/sasdeployment_custom_resource.yaml
  roles/vdm/tasks/validations.yaml
Labels: documentation, enhancement

#399 feat: (IAC-903) Update Cluster Autoscaler for EKS 1.25 Support
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cluster-autoscaler.yaml
  roles/baseline/tasks/main.yaml
Labels: documentation, enhancement

#397 fix: (IAC-917) cluster_logging install fails when V4_CFG_MANAGE_STORAGE is not explicitly defined
  roles/monitoring/defaults/main.yaml
Labels: bug
