Repository sassoftware/viya4-deployment, pull requests merged in 2023-05, with the labels that each got.

#435 feat: (IAC-696) DAC - Install gke-gcloud-auth-plugin with viya4-deployment for K8s v1.26
  Dockerfile
  README.md
  docker-entrypoint.sh
  docs/user/Dependencies.md
  docs/user/Kubeconfig.md
  roles/common/tasks/main.yaml
  roles/vdm/tasks/deploy.yaml
Labels: documentation, enhancement

#440 docs: (IAC-1028) Troubleshooting entry for AWS & GCP non-static kubeconfig files using ansible with orchestration deploy command
  docs/Troubleshooting.md
Labels: documentation

#442 6.6.0 - May 18, 2023
  Dockerfile
  README.md
  docker-entrypoint.sh
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/Dependencies.md
  docs/user/DockerVolumeMounts.md
  docs/user/Kubeconfig.md
  examples/multi-tenancy/openldap/openldap-modify-mt-users-groups.yaml
  examples/openldap/openldap-modify-users.yaml
  roles/baseline/defaults/main.yml
  roles/common/tasks/main.yaml
  roles/monitoring/defaults/main.yaml
  roles/monitoring/tasks/cluster-logging-common.yaml
  roles/monitoring/tasks/cluster-logging-custom-config.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring-common.yaml
  roles/monitoring/tasks/cluster-monitoring-custom-config.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/deploy.yaml
  roles/vdm/templates/generators/openldap-bootstrap-config.yaml
  roles/vdm/templates/generators/openldap-bootstrap-mt-config.yaml
Labels: bug, documentation, enhancement

#449 6.7.0 - May 25, 2023
  Dockerfile
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
Labels: bug

#447 (IAC-1016): fix: Offboarding tenants failure in back-to-back operations
  roles/multi-tenancy/tasks/multi-tenant-setup.yaml
Labels: bug

#444 fix: (IAC-994) Add K8S Cluster name to dynamic volumes created by EBS CSI Driver
  roles/baseline/defaults/main.yml
Labels: bug
