Repository sassoftware/viya4-deployment, pull requests merged in 2023-04, with the labels that each got.

#421 fix: (IAC-956) Handle Special Characters for Orchestration Credentials
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  roles/orchestration-common/tasks/orchestration_tooling.yaml
Labels: bug, documentation

#431 doc: (IAC-956) Remove Leftover Phrase in Doc
  docs/CONFIG-VARS.md
Labels: documentation

#428 feat: (IAC-298) Security update - `use-forwarded-headers` set to false for ingress-ngnix
  docs/Troubleshooting.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#419 fix: Update kubernetes-sigs nfs-provisioner
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#430 feat: (IAC-993) Add support for below the line deployment
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/deploy.yaml
Labels: enhancement

#427 fix: (IAC-358) Update uidNumber for test users in example LDAP confs
  examples/multi-tenancy/openldap/openldap-modify-mt-users-groups.yaml
  examples/openldap/openldap-modify-users.yaml
  roles/vdm/templates/generators/openldap-bootstrap-config.yaml
  roles/vdm/templates/generators/openldap-bootstrap-mt-config.yaml
Labels: bug

#433 feat: (IAC-1002) Upgrade the default ingress-nginx and kubectl versions to work with K8s 1.26
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#429 feat: (IAC-180) Add V4M_CUSTOM_CONFIG_USER_DIR config var for ops4viya logging & monitoring custom configurations
  docs/CONFIG-VARS.md
  docs/user/DockerVolumeMounts.md
  roles/monitoring/defaults/main.yaml
  roles/monitoring/tasks/cluster-logging-common.yaml
  roles/monitoring/tasks/cluster-logging-custom-config.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring-common.yaml
  roles/monitoring/tasks/cluster-monitoring-custom-config.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
Labels: documentation, enhancement
