Repository sassoftware/viya4-deployment, pull requests merged in 2024-04, with the labels that each got.

#539 feat: (IAC-1372) Update Default CERT_MANAGER_CHART_VERSION to 1.14.4
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: documentation, enhancement

#538 feat: (IAC-1344) (IAC-1363) Add support for K8s 1.29
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/cluster-autoscaler.yaml
Labels: enhancement

#541 feat: (IAC-1424) Update Google Cloud CLI version to be in sync with viya4-iac-gcp
  Dockerfile
  docs/user/Dependencies.md
Labels: documentation, enhancement

#543 docs: (IAC-1337) Add EC2 LB Tagging Documentation
  docs/Troubleshooting.md
Labels: documentation

#547 feat: (IAC-1449) Update Google Cloud CLI version to be in sync with viya4-iac-gcp
  Dockerfile
  docs/user/Dependencies.md
Labels: documentation, enhancement
