Repository sassoftware/viya4-deployment, pull requests merged in 2024-01, with the labels that each got.

#513 feat: (IAC-1291) METRICS_SERVER_CHART_VERSION default to 6.6.5
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#514 feat: (IAC-1188) Update CLUSTER_AUTOSCALER_CHART_VERSION default to 9.34.1
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#515 docs: (IAC-1308) Update CLUSTER_AUTOSCALER_CHART_VERSION documentation
  docs/CONFIG-VARS.md
Labels: documentation

#512 feat: (IAC-1266) (IAC-1186) Update kubectl to 1.27 and add support for ingress-nginx v1.9.X
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: enhancement

#518 6.16.0 - January 19, 2024
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: documentation, enhancement

#520 feat: (IAC-1329) Update Google Cloud CLI version to be in sync with viya4-iac-gcp
  Dockerfile
  docs/user/Dependencies.md
Labels: enhancement

#522 docs: (IAC-1304) Remove Experimental from PostgreSQL Doc
  docs/user/PostgreSQL.md
Labels: documentation

#521 fix: (IAC-1335) Resolve: doc is missing path: "/spec/volumeClaimTemplates/0/spec/storageClassName" error
  requirements.txt
  roles/vdm/templates/transformers/sas-storageclass.yaml
Labels: bug
