Repository sassoftware/viya4-deployment, pull requests merged in 2024-03, with the labels that each got.

#531 feat: (IAC-1375) Edit Ingress Definitions for Alertmanager To Adapt Changes From Viya Monitoring
  roles/monitoring/templates/host-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user-values-prom-operator.yaml
Labels: enhancement

#530 feat: (IAC-1236) Dependency version update
  Dockerfile
  docs/user/Dependencies.md
  requirements.txt
  requirements.yaml
Labels: enhancement

#532 docs: (IAC-1294) Add Note about sitedefault When Not Using Embedded LDAP
  docs/CONFIG-VARS.md
Labels: documentation

#533 chore: (IAC-1342) Disable Blank GitHub Issues & Add Feature Request Template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue--bug-report.yml
  .github/ISSUE_TEMPLATE/issue--feature-request.yml
Labels: enhancement

#534 docs: (IAC-1236) Updated Dependencies.md file with correct versions
  docs/user/Dependencies.md
Labels: documentation

#535 6.18.0 - March 21, 2024
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue--bug-report.yml
  .github/ISSUE_TEMPLATE/issue--feature-request.yml
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  requirements.txt
  requirements.yaml
  roles/monitoring/templates/host-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user-values-prom-operator.yaml
Labels: documentation, enhancement

#536 fix: (IAC-1420) add debian revision to gcp_cli_version arg in Dockerfile
  Dockerfile
Labels: bug
