Repository sassoftware/viya4-deployment, pull requests merged in 2024-02, with the labels that each got.

#523 feat: (IAC-1310) Dependency version update to resolve security vulnerability
  Dockerfile
  docs/user/Dependencies.md
  requirements.txt
  requirements.yaml
Labels: enhancement

#525 fix: (IAC-1362) Fix the V4M_ROUTING Validation Task
  roles/monitoring/tasks/main.yaml
Labels: bug

#524 docs: (IAC-1302) Deployment fails when following DAC SingleStore.md
  docs/user/SingleStore.md
Labels: documentation

#526 feat: (IAC-897) Annotate NGINX to indicate the desired subnets to provision LBs internal IP addrs from
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
Labels: enhancement

#527 feat: (IAC-897) Update variable doc for internal ticket testing comments
  docs/CONFIG-VARS.md
Labels: enhancement

#528 6.17.0 - February 15, 2024
  Dockerfile
  docs/CONFIG-VARS.md
  docs/user/Dependencies.md
  docs/user/PostgreSQL.md
  docs/user/SingleStore.md
  requirements.txt
  requirements.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/ingress-nginx.yaml
  roles/monitoring/tasks/main.yaml
  roles/vdm/templates/transformers/sas-storageclass.yaml
Labels: bug, documentation, enhancement
