Repository sassoftware/viya4-deployment, pull requests merged in 2024-07, with the labels that each got.

#562 docs: (SINGLESTORE-2165) Update SingleStore.md
  docs/user/SingleStore.md
Labels: documentation

#559 fix: (PSKD-398) Update v4m storage class deletion behavior
  roles/monitoring/tasks/main.yaml
Labels: bug

#563 6.21.0 - July 22, 2024
  Dockerfile
  requirements.txt
  requirements.yaml
  roles/monitoring/tasks/main.yaml
Labels: bug, enhancement
