Repository sassoftware/viya4-deployment, pull requests merged in 2024-08, with the labels that each got.

#566 feat: Create NIST_FEATURES_ENABLED flag for NIST effort
  roles/baseline/defaults/main.yml
  roles/common/defaults/main.yml
  roles/vdm/defaults/main.yaml
Labels: enhancement

#565 feat: add annotation for external database (PSKD-407)
  roles/vdm/templates/transformers/dataserver-transformer.yaml
Labels: enhancement

#568 docs: (PSKD-615) Documenting upcoming sas-data-server-operator change
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/PostgreSQL.md
Labels: documentation

#567 feat: (PSKD-503) Update DaC ingress-nginx version for K8s 1.30 support
  docs/CONFIG-VARS.md
  roles/baseline/defaults/main.yml
Labels: enhancement

#570 7.0.0 - August 29, 2024
  Dockerfile
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/Dependencies.md
  docs/user/PostgreSQL.md
  roles/baseline/defaults/main.yml
  roles/vdm/templates/transformers/dataserver-transformer.yaml
Labels: documentation, enhancement
