Repository sassoftware/viya4-deployment, pull requests merged in 2024-10, with the labels that each got.

#576 fix: (PSKD-640) Fixed file path for Workload Orchestrator
  roles/vdm/tasks/workload_orchestrator.yaml
Labels: bug

#577 feat: (PSKD-729) Removed experimental Azure Service Bus support
  roles/common/tasks/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/message_broker.yaml
Labels: enhancement

#579 7.1.0 - October 31, 2024
  Dockerfile
  docs/user/Dependencies.md
  requirements.txt
  requirements.yaml
  roles/common/tasks/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/main.yaml
  roles/vdm/tasks/message_broker.yaml
  roles/vdm/tasks/workload_orchestrator.yaml
Labels: bug, documentation, enhancement, dependencies
