Repository sassoftware/viya4-deployment, pull requests merged in 2025-03, with the labels that each got.

#597 chore: Remove optional component included and executed from DaC
  README.md
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/AnsibleUsage.md
  docs/user/DockerUsage.md
  docs/user/DockerVolumeMounts.md
  examples/ansible-vars-iac.yaml
  playbooks/playbook.yaml
  roles/common/tasks/task-validations.yaml
  roles/monitoring/defaults/main.yaml
  roles/monitoring/files/aws-storageclass.yaml
  roles/monitoring/files/azure-storageclass.yaml
  roles/monitoring/files/gcp-storageclass.yaml
  roles/monitoring/tasks/cluster-logging-common.yaml
  roles/monitoring/tasks/cluster-logging-custom-config.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring-common.yaml
  roles/monitoring/tasks/cluster-monitoring-custom-config.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/monitoring/tasks/viya-monitoring.yaml
  roles/monitoring/templates/host-based/user-values-opensearch.yaml
  roles/monitoring/templates/host-based/user-values-osd.yaml
  roles/monitoring/templates/host-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user-values-opensearch.yaml
  roles/monitoring/templates/path-based/user-values-osd.yaml
  roles/monitoring/templates/path-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user.env
  roles/monitoring/vars/main.yaml
Labels: documentation, enhancement

#598 docs: Use block storage for Crunchy Postgres (PSKD-1282)
  docs/CONFIG-VARS.md
Labels: documentation

#602 docs: Update TOC block storage entries (PSKD-1025)
  docs/CONFIG-VARS.md
Labels: documentation

#603 8.0.0 - March 19, 2025
  Dockerfile
  README.md
  docs/CONFIG-VARS.md
  docs/Troubleshooting.md
  docs/user/AnsibleUsage.md
  docs/user/DockerUsage.md
  docs/user/DockerVolumeMounts.md
  examples/ansible-vars-iac.yaml
  playbooks/playbook.yaml
  roles/baseline/defaults/main.yml
  roles/baseline/tasks/main.yaml
  roles/baseline/tasks/nfs-subdir-external-provisioner.yaml
  roles/baseline/tasks/storage-classes.yaml
  roles/common/tasks/task-validations.yaml
  roles/monitoring/defaults/main.yaml
  roles/monitoring/files/aws-storageclass.yaml
  roles/monitoring/files/azure-storageclass.yaml
  roles/monitoring/files/gcp-storageclass.yaml
  roles/monitoring/tasks/cluster-logging-common.yaml
  roles/monitoring/tasks/cluster-logging-custom-config.yaml
  roles/monitoring/tasks/cluster-logging.yaml
  roles/monitoring/tasks/cluster-monitoring-common.yaml
  roles/monitoring/tasks/cluster-monitoring-custom-config.yaml
  roles/monitoring/tasks/cluster-monitoring.yaml
  roles/monitoring/tasks/main.yaml
  roles/monitoring/tasks/viya-monitoring.yaml
  roles/monitoring/templates/host-based/user-values-opensearch.yaml
  roles/monitoring/templates/host-based/user-values-osd.yaml
  roles/monitoring/templates/host-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user-values-opensearch.yaml
  roles/monitoring/templates/path-based/user-values-osd.yaml
  roles/monitoring/templates/path-based/user-values-prom-operator.yaml
  roles/monitoring/templates/path-based/user.env
  roles/monitoring/vars/main.yaml
  roles/vdm/defaults/main.yaml
  roles/vdm/tasks/postgres/postgres-instance.yaml
  roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
  roles/vdm/templates/transformers/sas-storageclass.yaml
Labels: documentation, enhancement

#614 ci: (PSKD-1515) add release workflows
  .github/release-drafter.yml
  .github/workflows/conventional-commits.yml
  .github/workflows/draft-release.yml
  .github/workflows/semvar.yml
Labels: CI/CD
